#  Agent Information
agent:
  name: RAG Agent
  description: AI Agent RAG Agent Project.
  version: 0.2.0

# Plugins configuration
# Plugins Configuration
plugins:
  - plugin_id: rag
    name: "RAG Search & Retrieval"
    description: "Semantic search and document retrieval"

    # NEW: Explicit capability configuration with scope requirements
    capabilities:
      - capability_id: index_document
        required_scopes: ["rag:access"]
      - capability_id: semantic_search
        required_scopes: ["rag:access"]
      - capability_id: ask_documents
        required_scopes: ["rag:access"]
      - capability_id: list_collections
        required_scopes: ["rag:access"]

    config:
      # Embedding backend configuration
      embedding_backend: "openai"
      embedding_config:
        model: "text-embedding-3-small"
        api_key: "${OPENAI_API_KEY}"
        batch_size: 100
        rate_limit: 1000

      # Vector store backend configuration
      vector_backend: "memory"
      vector_config:
        similarity_metric: "cosine"
        persist_path: "./vector_index.pkl"
        auto_save: true
        save_interval: 300

      # Document processing configuration
      chunking:
        strategy: "recursive"
        chunk_size: 1000
        chunk_overlap: 200
        separators: ["\n\n", "\n", ".", "!", "?"]

      # Search configuration
      search:
        default_k: 5
        max_k: 100
        similarity_threshold: 0.0
        include_metadata: true

      # RAG configuration
      rag:
        max_context_length: 4000
        include_sources: true

      # Collection management
      collections:
        default_collection: "documents"
        auto_create: true
        max_collections: 10

# Routing configuration
routing:
  default_mode: ai  # Use AI routing when AI provider is configured

# AI configuration
ai_provider:
    provider: openai
    api_key: ${OPENAI_API_KEY}
    model: gpt-4o-mini
    temperature: 0.7
    max_tokens: 1000
    top_p: 1.0

# AI system prompt and configuration
ai:
  enabled: true
  system_prompt: |
    You are a helpful AI assistant created by AgentUp.

    Your role:
    - Understand user requests naturally
    - Provide helpful, accurate responses
    - Maintain a friendly and professional tone
    - Use available functions when appropriate
    - Keep responses concise and relevant

    Always be helpful, accurate, and maintain context in conversations.


# Unified security configuration for minimal template
security:
  enabled: true
  type: api_key
  auth:
    # Default to API key authentication
    api_key:
      header_name: "X-API-Key"
      location: "header"  # Options: header, query, cookie
      keys:
        - key: "your-key"
          scopes: ["api:read", "api:write", "system:read", "rag:access"]  # Permissions for demo plugin
  # Basic scope hierarchy for minimal template
  scope_hierarchy:
    admin: ["*"]        # Admin has all permissions
    api:write: ["api:read"]   # Write access includes read
    api:read: []        # Basic read access
    system:read: []     # System information access
    files:read: []      # File read access
    rag:access: []      # RAG plugin access

# Cache configuration

# Simple context-aware middleware for minimal template
middleware:
  - name: timed
    params: {}

# Push notifications configuration
push_notifications:
  enabled: false


# State management configuration
# State management disabled for minimal template
state_management:
  enabled: false


# Logging configuration
logging:
  enabled: true
  level: "INFO"
  format: "text"  # Simple text format for minimal template

  # Console output settings
  console:
    enabled: true
    colors: true

  # File logging disabled for minimal template
  file:
    enabled: false

  # Basic features for minimal template
  correlation_id: false       # Disabled for simplicity
  request_logging: false      # Disabled for simplicity

  # Uvicorn integration
  uvicorn:
    access_log: false         # Minimal logging
    disable_default_handlers: true

# Development configuration
development:
  enabled: false  # Keep all development features disabled by default

  # Filesystem plugins remain disabled for security
  filesystem_plugins:
    enabled: false
    allowed_directories:
      - ~/.agentup/plugins
